name = "test-sk-og"
account_id = "394fea48b28fa3f0d4751e6a12240570"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "pnpm run build"

compatibility_date = "2023-06-05"
compatibility_flags = [ "nodejs_compat" ]
node_compat = true

workers_dev = true
